from django.conf.urls import url
from django.contrib.auth import views as auth_views
from tragether import views
from tragether import forms

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^create_new_travel$', views.create_new_travel, name='create_new_travel'),
    url(r'^travel_group/(?P<pk>[0-9]+)$', views.travel_group, name='travel_group'),
    url(r'^my_travel$', views.my_travel, name='my_travel'),
    url(r'^users_profile/(?P<user>\w+)$', views.users_profile, name='users_profile'),
    url(r'^edit_profile$', views.edit_profile, name='edit_profile'),
    url(r'^edit_travel/(?P<travel_id>\d+)$', views.edit_travel, name='edit_travel'),
    url(r'^welcome$', auth_views.login, {'template_name':'tragether/welcome.html', 
        'extra_context':{'form_register': forms.RegistrationForm(), 
        'form_reset': forms.EmailForm()}, 'redirect_authenticated_user':True}, 
        name='login'),
    url(r'^register$', views.register, name='register'),
    url(r'^register/confirm/(?P<username>.+)/(?P<token>.+)$', views.register_confirm, name='register_confirm'),
    url(r'^password-reset$', views.reset_password, name='reset_password'),
    url(r'^password-reset/confirm/(?P<username>.+)/(?P<token>.+)$', views.reset_password_confirm, name='reset_password_confirm'),
    url(r'^logout$', auth_views.logout_then_login, name='logout'),
    url(r'^apply_travel/(?P<pk>[0-9]+)$', views.apply_travel, name='apply_travel'),
    url(r'^apply_unread_message$', views.apply_unread_message, name='apply_unread_message'),
    url(r'^apply_history_message$', views.apply_history_message, name='apply_history_message'),
    url(r'^applied_message$', views.applied_message, name='applied_message'),
    url(r'^accept_apply_message/(?P<user>\w+)/(?P<pk>[0-9]+)$', views.accept_apply_message,
        name='accept_apply_message'),
    url(r'^refuse_apply_message/(?P<pk>[0-9]+)$', views.refuse_apply_message,
        name='refuse_apply_message'),
    url(r'^vote_attraction$', views.vote_attraction, name='vote_attraction'),
    url(r'^get_unread_message$', views.get_unread_message, name='get_unread_message'),
    url(r'^add-chatbox-msg/(?P<travel_id>\d+)$', views.add_chatbox_msg),
    url(r'^get-chatbox-msg/(?P<travel_id>\d+)$', views.get_chatbox_msg),
    url(r'^add-itinerary/(?P<travel_id>\d+)$', views.add_itinerary),
    url(r'^get-itinerary/(?P<travel_id>\d+)$', views.get_itinerary),
    url(r'^delete-itinerary/(?P<itinerary_id>\d+)$', views.delete_itinerary),
    url(r'^edit-itinerary/(?P<itinerary_id>\d+)$', views.edit_itinerary),
    url(r'^update-itinerary/(?P<travel_id>\d+)$', views.update_itinerary),
    url(r'^update-itinerary/(?P<travel_id>\d+)/(?P<time>.+)$', views.update_itinerary),
    url(r'^invite_travel/(?P<pk>[0-9]+)$', views.invite_travel, name='invite_travel'),
    url(r'^invite_unread_message$', views.invite_unread_message, name='invite_unread_message'),
    url(r'^invite_history_message$', views.invite_history_message, name='invite_history_message'),
    url(r'^invited_message$', views.invited_message, name='invited_message'),
    url(r'^accept_invite_message/(?P<pk>[0-9]+)$', views.accept_invite_message,
        name='accept_invite_message'),
    url(r'^refuse_invite_message/(?P<pk>[0-9]+)$', views.refuse_invite_message,
        name='refuse_invite_message'),
]
